### ISSUE TITLE
Header color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/fitnesstrainer#4]
The color pallets for the header's following options do not fully appear :
Header menu color : https://prnt.sc/uxrb9w
Header menu hover color : https://prnt.sc/uxrbhi
Header menu hover shade color : https://prnt.sc/uxrbot

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
