### ISSUE TITLE
Footer page color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/fitnesstrainer#8]
If we to change the color on the following elements on the footer, we will not see the full color pallet :
Footer Social icon Color : https://prnt.sc/uxs11f
Footer Social Icon Hover BG Color : https://prnt.sc/uxs18s
Footer Social icon Hover Color: https://prnt.sc/uxs1g9

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
